#### numpy와 닮은 파이토치 pytorch

In [1]:
import torch
a=torch.tensor([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=torch.tensor([1,2,3.1,4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [2]:
A=torch.tensor([[1,2,3],[3,4,5]]) # 이 셀부터는 import torch는 실행했다고 작성
# A=torch.tensor([[1,2],[4,5,6]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 갯수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원 수
print(A.numel()) # 총 원소의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [3]:
print(torch.zeros(5))
print(torch.zeros_like(A)) # A행렬과 동일한 모양으로 0을 채움
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3,10,2)) # range랑 같은데 tensor로 만들어줌
print(torch.arange(0,1,0.1)) #소수점 가능
print(torch.linspace(0,1,10)) # 0에서부터 1 포함 10개로


tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [4]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c)

tensor([5, 7, 9])


In [5]:
A=torch.tensor([[1,2,3],[4,5,6]])
B=torch.tensor([[4,5,6],[7,8,9]])
C=A+B
D=A-B
print(C)
print(D)
print(A+B)
print(A*B) # 곱셈은 성분 곱, Hardmard product
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 성분 제곱

tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[-3, -3, -3],
        [-3, -3, -3]])
tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 4, 10, 18],
        [28, 40, 54]])
tensor([[0.2500, 0.4000, 0.5000],
        [0.5714, 0.6250, 0.6667]])
tensor([[16, 25, 36],
        [49, 64, 81]])


In [6]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


#### pytorch의 인덱싱과 슬라이딩

In [8]:
a=torch.tensor([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B = [[1,2,3,4],[5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # 리스트는 에러뜸
print(A[1,:]) # 1행, 전부
print(A[1,0:3:2]) # 1행, 0부터 3까지 2씩 증가
print(A[:,2]) # 2열, 전부
print(A[:][2]) # 2행, 전부

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [10]:
# 3차우너 행렬 인덱싱
A=torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]],
                 [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape)
print(A[0,1,2])

a=torch.tensor([[1,2,3,4]]) # 대괄호가 하나 늘어나면 왼쪽에 shape이 추가됨
print(a.shape)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 4])


#### 리스트로 인덱싱

In [11]:
print(A)
A[[0,1,1,0],[0,1,2,1],[3,3,2,1]]

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


tensor([ 3, 19, 22,  5])

In [14]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러 개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A>3) # 리스트와 달리 각 성분에 대한 비교해줌
print(A[A>3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A>3] = 100
print(A) # 그러면 이런 것도 가능하다! (3보다 큰 애들을 100으로 바꿔줘)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True,False,False,True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[ [True,True,False,False]])
c = [1,2,3,4]
# c[[True,True,False,False]] # 리스트는 이렇게 하면 안됨

False
tensor([[False, False, False,  True],
        [ True, False,  True, False]])
tensor([4, 5, 7])
tensor([[  1,   2,   3, 100],
        [100,   3, 100,   3]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [17]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[torch.tensor(2)] # torch.tensor를 안에다가?
print(A)
A=a[torch.tensor([2,3,4])]
print(A)
A=a[torch.tensor([[2,2,2],[3,3,3]])]
print(A)

a=[1,2,3]
# a[[1,1,1,1,2,2,2]] # error!

a=torch.tensor([[1,2,3],[4,5,6]])
print(a[torch.tensor(0)])
A=a[torch.tensor([[0,1],[1,1]])]
print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2,"3"이 된다!
print(A)

# segmentation 결과 그림 보여줄 때 사용!
b=torch.tensor([[225,225,0],[0,255,0],[0,0,255],[255,0,255],[70,80,75],[0,0,4],[60,100,255]])
import matplotlib.pyplot as plt
plt.imshow(b[torch.tensor([[0,1],[1,1]])])



tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


: 