In [14]:
import numpy as np

In [15]:
P = 15 # W
e = 1.6022e-19 # C
ne_i = 1e6
p = 101325 # Pa
kb = 1.38e-17 # J/K
T = 400 #K
V = 13.6
m = 3.5552e23

In [16]:
n = p/kb/T


In [17]:
sig = e*ne_i*m/n

In [18]:
sig

3.103153293737972e-09

In [19]:
(15/sig/13.6)**0.5/n/1e-17

102.70628620098769

In [20]:
(P/V/sig)**0.5

18852.743567599784

In [21]:
V = 13.6
Fv = np.array([50,100,200,300])
Fvm = Fv/60
tr = V/Fvm
tr


array([16.32,  8.16,  4.08,  2.72])

In [26]:
conv = np.array([10.59278, 12.60309, 15.20619, 18.81443, 21.59794])
C2H6 = np.array([33.69427, 34.93631,36.27389,37.19745,42.89809])
H2 = np.array([19.07643,22.80255,28.21656,33.3121,36.81529])
C2 = np.array([19.07643,16.30573,15.5414,14.77707,14.61783])
C4 = np.array([12.7707,14.61783,16.97452,17.89809,19.26752])
C3 = np.array([0.955414,1.178344,1.464968,1.687898,1.910828])

In [23]:
total = C2H6 + C2 + C4+ C3

In [27]:
100-total

array([33.503186, 32.961786, 29.745222, 28.439492, 21.305732])

In [29]:
C42 = C4 + 100 - total
C42

array([46.273886, 47.579616, 46.719742, 46.337582, 40.573252])